sudo    : required
language: generic 
services:
    - docker
    
before_install:
    - docker build -t lochan/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true lochan/docker-react npm run test